### ISSUE TITLE
Multi-Language tag error

### ISSUE THREAD

**Issue by Koubek** [NAVDOCKER/SPECIFIC#2]
@freddydk There is a mistake in #1. Obviously, it is not possible to use `:` (colon) character inside the tag itself. You can use `.` (dot) or `-` (minus) instead. I would make this change by myself but I prefer you decide what character fits better.

**Comment by freddydk** [comment]
Ok, i have made a few other changes, so I will fix this, thanks

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Koubek** [comment]
OK, I have seen the changes.

**Comment by Koubek** [comment]
BTW, you can check for example [dotnet docker image tagging](https://hub.docker.com/r/microsoft/dotnet/tags/) as an example/inspiration.

**Comment by freddydk** [comment]
All specific images are tagged with the version number of NAV, which is installed. The following list of examples explains the tagging strategy:
•	navdocker.azurecr.io/dynamics-nav:2017 will give you the latest NAV 2017 W1 version.
•	navdocker.azurecr.io/dynamics-nav:2017-cu8 will give you NAV 2017 CU8 W1 version.
•	navdocker.azurecr.io/dynamics-nav:2017-dk will give you the latest NAV 2017 DK version.
•	navdocker.azurecr.io/dynamics-nav:2017-cu8-dk will give you NAV 2017 CU8 DK version.
•	navdocker.azurecr.io/dynamics-nav:10.0.17501.0 will give you a specific build of NAV (in this case, NAV 2017 CU8 W1).
•	navdocker.azurecr.io/dynamics-nav:10.0.17501.0-dk will give you a specific DK build of NAV (in this case, NAV 2017 CU8 DK).
There is no such thing as dynamics-nav:latest at this time, instead you can get the latest NAV 2016, the latest NAV 2017 etc.
For this test period, the navdocker.azurecr.io registry contains the following images:
•	NAV 2017 CU8 all languages
•	NAV 2017 CU7 W1
•	NAV 2017 CU7 DK
•	NAV 2016 CU20 W1
•	devpreview july update
If you are wondering about the tagging of devpreview, it really follows the tagging examples above:
•	navdocker.azurecr.io/dynamics-nav:devpreview to get the latest devpreview version
•	navdocker.azurecr.io/dynamics-nav:devpreview-july to get the july update

**Comment by Koubek** [comment]
OK, great. But still can`t download language related containers:
![image](https://user-images.githubusercontent.com/24265973/29005734-e6297788-7ae1-11e7-85dc-2e15cb671862.png)

**Comment by freddydk** [comment]
Oups – something went wrong on pushing the extra tags.

NAV 2017CU8DK is available as 10.0.17501.0-DK
I will check what went wrong during build/push.

/Freddy

**Comment by freddydk** [comment]
Should work now.

/Freddy

From: Freddy Kristiansen
Sent: 6. august 2017 20:22
To: 'NAVDOCKER/SPECIFIC' <reply@reply.github.com>; NAVDOCKER/SPECIFIC <SPECIFIC@noreply.github.com>
Cc: State change <state_change@noreply.github.com>
Subject: RE: [NAVDOCKER/SPECIFIC] Multi-Language tag error (#2)

Oups – something went wrong on pushing the extra tags.

NAV 2017CU8DK is available as 10.0.17501.0-DK
I will check what went wrong during build/push.

/Freddy
